// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using mentoring;

namespace MentoriaCSharp.Migrations
{
    [DbContext(typeof(MentoriaContext))]
    partial class MentoriaContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("mentoring.Instituition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name")
                        .HasMaxLength(100);

                    b.HasKey("Id");

                    b.ToTable("Instituitions");
                });

            modelBuilder.Entity("mentoring.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("InstituitionId");

                    b.Property<string>("Name")
                        .HasMaxLength(100);

                    b.HasKey("Id");

                    b.HasIndex("InstituitionId");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("mentoring.Student", b =>
                {
                    b.HasOne("mentoring.Instituition", "Instituition")
                        .WithMany()
                        .HasForeignKey("InstituitionId");
                });
#pragma warning restore 612, 618
        }
    }
}
