// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Nota10.Data;

namespace Nota10.Migrations
{
    [DbContext(typeof(Nota10Context))]
    partial class Nota10ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Nota10.Models.ClassRoom", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("InstituitionId");

                    b.Property<string>("Name")
                        .HasMaxLength(100);

                    b.Property<short>("SchoolYear");

                    b.HasKey("Id");

                    b.HasIndex("InstituitionId");

                    b.ToTable("ClassRooms");
                });

            modelBuilder.Entity("Nota10.Models.Instituition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name")
                        .HasMaxLength(100);

                    b.HasKey("Id");

                    b.ToTable("Instituitions");
                });

            modelBuilder.Entity("Nota10.Models.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("BirthDate");

                    b.Property<int?>("ClassRoomId");

                    b.Property<string>("Name")
                        .HasMaxLength(100);

                    b.HasKey("Id");

                    b.HasIndex("ClassRoomId");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("Nota10.Models.ClassRoom", b =>
                {
                    b.HasOne("Nota10.Models.Instituition", "Instituition")
                        .WithMany()
                        .HasForeignKey("InstituitionId");
                });

            modelBuilder.Entity("Nota10.Models.Student", b =>
                {
                    b.HasOne("Nota10.Models.ClassRoom", "ClassRoom")
                        .WithMany()
                        .HasForeignKey("ClassRoomId");
                });
#pragma warning restore 612, 618
        }
    }
}
